# Generated by Django 2.2.6 on 2019-10-16 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_estate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
    ]
