# Generated by Django 2.2.6 on 2019-10-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_estate', '0002_delete_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouts',
            name='text_slide',
            field=models.CharField(max_length=250, verbose_name='text a cote du slide '),
        ),
    ]
