# Generated by Django 2.2.6 on 2019-10-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='maps',
            field=models.CharField(max_length=200),
        ),
    ]
