# Generated by Django 2.2.6 on 2019-10-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='short',
            field=models.CharField(blank=True, max_length=100, verbose_name='courte description'),
        ),
    ]
