# Generated by Django 2.2.6 on 2019-10-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_video_lien'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='thumb', verbose_name='image du haut'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video', verbose_name='image du bas'),
        ),
    ]
