# Generated by Django 2.2.6 on 2019-10-16 13:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20191016_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('titre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'specification',
                'verbose_name_plural': 'vues',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('size', models.PositiveIntegerField()),
                ('Beds', models.PositiveIntegerField()),
                ('Baths', models.PositiveIntegerField()),
                ('Garage', models.PositiveIntegerField()),
                ('taxe_include', models.BooleanField(default=True)),
                ('oreviews', tinymce.models.HTMLField(verbose_name='oreviviews')),
                ('specification', models.ManyToManyField(to='house.Specification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
