# Generated by Django 2.2.6 on 2019-10-16 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0009_auto_20191016_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maison',
            name='interior',
        ),
        migrations.RemoveField(
            model_name='maison',
            name='piscine',
        ),
        migrations.AddField(
            model_name='maison',
            name='interiors',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='interieur', to='house.Interior', verbose_name='photo interieur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maison',
            name='piscines',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='piscine', to='house.Piscine', verbose_name='photo piscine'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='maison',
            name='vues',
        ),
        migrations.AddField(
            model_name='maison',
            name='vues',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vues', to='house.Vues', verbose_name='photo vue'),
            preserve_default=False,
        ),
    ]
